<?php

namespace HandissimoBundle\Repository;

/**
 * AlertContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertContentRepository extends \Doctrine\ORM\EntityRepository
{
}
