<?php

namespace HandissimoBundle\Repository;

/**
 * BrochuresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrochuresRepository extends \Doctrine\ORM\EntityRepository
{
}
