<?php

namespace HandissimoBundle\Repository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatitude($name)
    {
        $query = $this->createQueryBuilder('c')
            ->select('c.latitude')
            ->addSelect('c.name')
            ->where('c.name = ?1')
            ->setParameter(1, $name)
            ->getQuery();
        return $query->getResult();
    }

    public function getLongitude($name)
    {
        $query = $this->createQueryBuilder('c')
            ->select('c.longitude')
            ->where('c.name = ?1')
            ->setParameter(1,  $name)
            ->getQuery();
        return $query->getResult();
    }

    public function getByCity($city)
    {
        /*$em = $this->getEntityManager();
      $query = $em->createQueryBuilder();
      $query->select('c.name', 'c.postal');
      $query->from('HandissimoBundle:City', 'c');
      $query->where('c.name LIKE :namedata');
      $query->setParameter('namedata', '%'.$city.'%');
      $query->andWhere('c.postal LIKE :postaldata');
      $query->setParameter('postaldata', '%'.$city.'%');
      $query->groupBy('c.postal', 'c.name');
      $query->setMaxResults()*/
        $regex = '^'.$city;
      $qb = $this->createQueryBuilder('c')
          ->select('c.name', 'c.postal')
          ->where('REGEXP(c.name, :regexp) = true')
          ->setParameter('regexp', $regex)
          ->orWhere('c.postal LIKE :postaldata')
          ->setParameter('postaldata', '%'.$city.'%')
          ->groupBy('c.postal', 'c.name')
          ->setMaxResults(10)
          ->getQuery();
      return $qb->getResult();
    }
}
