<?php

namespace HandissimoBundle\Repository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatitude($name)
    {
        $query = $this->createQueryBuilder('c')
            ->select('c.latitude')
            ->addSelect('c.name')
            ->where('c.name = ?1')
            ->setParameter(1, $name)
            ->getQuery();
        return $query->getResult();
    }

    public function getLongitude($name)
    {
        $query = $this->createQueryBuilder('c')
            ->select('c.longitude')
            ->where('c.name = ?1')
            ->setParameter(1,  $name)
            ->getQuery();
        return $query->getResult();
    }
}
