<?php

namespace HandissimoBundle\Repository;

/**
 * CommentAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
