<?php

namespace HandissimoBundle\Repository;

/**
 * DisabilityTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisabilityTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
