<?php

namespace HandissimoBundle\Repository;

/**
 * EditContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditContentRepository extends \Doctrine\ORM\EntityRepository
{
}
