<?php

namespace HandissimoBundle\Repository;

/**
 * GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getById($id)
    {
        $query = $this->createQueryBuilder('g')
            ->where('g.user = ?1')
            ->setParameter(1, $id)
            ->getQuery();
        return $query->getResult();

    }
}
