<?php

namespace HandissimoBundle\Repository;


use Application\Sonata\UserBundle\Entity\User;
use HandissimoBundle\Entity\Media;
use HandissimoBundle\Entity\Organizations;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByUsers($userId, $caroussel = 1)
    {
        $query = $this->createQueryBuilder('m')
            ->where('m.user = ?1')
            ->where('m.caroussel = ?2')
            ->setParameter(1, $userId)
            ->setParameter(2, $caroussel)
            ->getQuery();
        return $query->getResult();
    }
}
