<?php
/**
 * Created by PhpStorm.
 * User: tangui
 * Date: 27/04/17
 * Time: 14:10
 */

namespace HandissimoBundle\Repository;
/**
 * NeedsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class NeedsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByNeed($needs)
    {
        $qb = $this->createQueryBuilder('n')
            ->select('n.needName')
            ->where('n.needName LIKE :namedata')
            ->setParameter('namedata', '%'.$needs.'%')
            ->getQuery();
        return $qb->getResult();
    }

    public function getNeedsById($id)
    {
        $query = $this->createQueryBuilder('n')
            ->select('n.needName')
            ->where('n.id = '.$id)
            ->getQuery();
        return $query->getSingleScalarResult();
    }
}