<?php

namespace HandissimoBundle\Repository;

/**
 * NeedsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NeedsRepository extends \Doctrine\ORM\EntityRepository
{
}
