<?php

namespace HandissimoBundle\Repository;

/**
 * OtherJobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtherJobRepository extends \Doctrine\ORM\EntityRepository
{
}
