<?php

namespace HandissimoBundle\Repository;

/**
 * SecondaryNeedsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecondaryNeedsRepository extends \Doctrine\ORM\EntityRepository
{
}
