<?php

namespace HandissimoBundle\Repository;

/**
 * SocialStaffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialStaffRepository extends \Doctrine\ORM\EntityRepository
{
}
