<?php

namespace HandissimoBundle\Repository;

/**
 * StaffTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaffTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
