<?php

namespace HandissimoBundle\Repository;

/**
 * StructureTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StructureTypeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByStructure($id)
    {

    }
}
