<?php

namespace HandissimoBundle\Repository;

/**
 * StructuresTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StructuresTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
