<?php

namespace HandissimoBundle\Repository;

/**
 * StructuresListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StructuresListRepository extends \Doctrine\ORM\EntityRepository
{
}
