<?php

namespace HandissimoBundle\Repository;

/**
 * StructuresListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StructuresListRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByStructure($keyword)
    {
        $query = $this->createQueryBuilder('s')
            ->select('s.name')
            ->where('s.name LIKE :structureData')
            ->setParameter('structureData', '%' . $keyword . '%')
            ->getQuery();
        return $query->getResult();

    }
}
