<?php

namespace HandissimoBundle\Repository;
use HandissimoBundle\Entity\StructuresList;
use HandissimoBundle\Entity\StructureType;

/**
 * StructuresListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StructuresListRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByType(StructureType $structuresList)
    {
        $query = $this->createQueryBuilder('sl')
            ->join('sl.type', 'st')
            ->where('st.id = :type')
            ->setParameter('type', $structuresList->getId())
            ->getQuery();
        return $query->getResult();
    }

    public function getStrucureById($id)
    {
        $query = $this->createQueryBuilder('sl')
            ->select('sl.name')
            ->where('sl.id = ' .$id)
            ->getQuery();
        return $query->getSingleResult();
    }
}
