handissimo_profile_version:
    path:   /version/{id}
    defaults: { _controller: "HandissimoBundle:Profile:organizationsVersion" }

handissimo_profile_list_organizations:
    path:   /list
    defaults: { _controller: "HandissimoBundle:Profile:listOrganizations" }

handissimo_profile_view_current_organization:
    path:   /view/{id}
    defaults: { _controller: "HandissimoBundle:Profile:viewCurrentOrganizations" }

handissimo_profile_compare_organizations:
    path:   /view/{id}/{rev}
    defaults: { _controller: "HandissimoBundle:Profile:viewDetailOld" }
