handissimo_opinion:
    resource: "@HandissimoBundle/Resources/config/routing/opinion.yml"
    prefix:   /opinion

handissimo_research:
    resource: "@HandissimoBundle/Resources/config/routing/research.yml"
    prefix:   /

handissimo_aboutpage:
    path:     /about
    defaults: { _controller: HandissimoBundle:Default:about }

handissimo_organizations_standard_page:
    resource: "@HandissimoBundle/Resources/config/routing/structure.yml"
    prefix: /structure/{id}

handissimo_structure:
    path: /solution
    defaults: { _controller: "HandissimoBundle:EditContent:howToUse" }

handissimo_notice:
    path: /mentions-légales
    defaults: { _controller: "HandissimoBundle:Default:notice" }

handissimo_profile_search:
    path:  /profile/search
    defaults: { _controller: "HandissimoBundle:Profile:profileSearch" }

search_profile:
    path:   /profile/search/ajax/{profileSearch}
    defaults: { _controller: "HandissimoBundle:Ajax:searchProfile"}
    methods: POST

handissimo_organizations:
    resource: "@HandissimoBundle/Resources/config/routing/organizations.yml"
    prefix:   /organizations

handissimo_media:
    resource: "@HandissimoBundle/Resources/config/routing/media.yml"
    prefix:   /media
