handissimo_opinion:
    resource: "@HandissimoBundle/Resources/config/routing/opinion.yml"
    prefix:   /opinion

handissimo_research:
    resource: "@HandissimoBundle/Resources/config/routing/research.yml"
    prefix:   /

handissimo_aboutpage:
    path:     /about
    defaults: { _controller: HandissimoBundle:Default:about }

handissimo_organizations_standard_page:
    resource: "@HandissimoBundle/Resources/config/routing/structure.yml"
    prefix: /structure/{id}

handissimo_structure:
    path: /solution
    defaults: { _controller: "HandissimoBundle:EditContent:howToUse" }

#handissimo_answer:
 #   path: /structure/{id}
  #  defaults: { _controller: "HandissimoBundle:Default:commentAnswer" }

load_database:
    path: /load
    defaults: { _controller: "HandissimoBundle:Default:load" }

handissimo_notice:
    path: /mentions-légales
    defaults: { _controller: "HandissimoBundle:Default:notice" }

handissimo_organizations:
    resource: "@HandissimoBundle/Resources/config/routing/organizations.yml"
    prefix:   /organizations
