handissimo_opinion:
    resource: "@HandissimoBundle/Resources/config/routing/opinion.yml"
    prefix:   /opinion

handissimo_research:
    resource: "@HandissimoBundle/Resources/config/routing/research.yml"
    prefix:   /

handissimo_aboutpage:
    path:     /about
    defaults: { _controller: HandissimoBundle:Default:about }

handissimo_organizations_standard_page:
    path: /structure/{id}
    defaults: { _controller: "HandissimoBundle:Default:standardPage" }

handissimo_structure:
    path: /solution
    defaults: { _controller: "HandissimoBundle:Default:structure" }

handissimo_answer:
    path: /structure/{id}
    defaults: { _controller: "HandissimoBundle:Default:commentAnswer" }

load_database:
    path: /load
    defaults: { _controller: "HandissimoBundle:Default:load" }

vote_like:
    path: /structure/{id}/like
    defaults: { _controller: "HandissimoBundle:Default:like" }