services:

    handissimo.captchaverify:
        class: HandissimoBundle\Services\Captcha\CaptchaVerify

    handissimo.admin.structure_type:
        class: HandissimoBundle\Admin\StructureTypeAdmin
        arguments: [~, HandissimoBundle\Entity\StructureType, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: StructureType }
