Application\Sonata\UserBundle\Entity\User:
   type:  entity
   table: fos_user
   id:
       id:
           type: integer
           generator:
               strategy: AUTO
   fields:
       avatar:
           type: text
           nullable: true

   oneToOne:
       organizationsuser:
           targetEntity: HandissimoBundle\Entity\Organizations
           mappedBy: userorg

       societyUser:
           targetEntity: HandissimoBundle\Entity\Society
           mappedBy: userSociety
