Application\Sonata\UserBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        userType:
            type: string
            nullable: false
            length: 50
        avatar:
            type: text
            nullable: true
        compact:
            type: boolean
            nullable: true

    oneToMany:
        organizationsuser:
            targetEntity: HandissimoBundle\Entity\Organizations
            mappedBy: userorg
            nullable: true

