<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @var string
     */
    private $userType;


    /**
     * Set userType
     *
     * @param string $userType
     *
     * @return User
     */
    public function setUserType($userType)
    {
        $this->userType = $userType;

        return $this;
    }

    /**
     * Get userType
     *
     * @return string
     */
    public function getUserType()
    {
        return $this->userType;
    }
    /**
     * @var string
     */
    private $avatar;


    /**
     * Set avatar
     *
     * @param string $avatar
     *
     * @return User
     */
    public function setAvatar($avatar)
    {
        $this->avatar = $avatar;

        return $this;
    }

    /**
     * Get avatar
     *
     * @return string
     */
    public function getAvatar()
    {
        return $this->avatar;
    }


    /**
     * @var boolean
     */
    private $compact;


    /**
     * Set compact
     *
     * @param boolean $compact
     *
     * @return User
     */
    public function setCompact($compact)
    {
        $this->compact = $compact;

        return $this;
    }

    /**
     * Get compact
     *
     * @return boolean
     */
    public function getCompact()
    {
        return $this->compact;
    }
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $organizationsuser;


    /**
     * Add organizationsuser
     *
     * @param \HandissimoBundle\Entity\Organizations $organizationsuser
     *
     * @return User
     */
    public function addOrganizationsuser(\HandissimoBundle\Entity\Organizations $organizationsuser)
    {
        $organizationsuser->setUserorg($this);
        $this->organizationsuser[] = $organizationsuser;

        return $this;
    }

    /**
     * Remove organizationsuser
     *
     * @param \HandissimoBundle\Entity\Organizations $organizationsuser
     */
    public function removeOrganizationsuser(\HandissimoBundle\Entity\Organizations $organizationsuser)
    {
        //$this->organizationsuser->removeElement($organizationsuser);
        foreach ($this->organizationsuser as $k => $v){
            if ($v->getId() == $organizationsuser->getId()){
                unset($this->organizationsuser[$k]);
            }
        }
    }

    /**
     * Get organizationsuser
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getOrganizationsuser()
    {
        return $this->organizationsuser;
    }

    public function setOrganizationuser($organizatiosuser)
    {
        $this->organizationsuser = $organizatiosuser;

        return $this;
    }

    public function __construct()
    {
        parent::__construct();
        $this->organizationsuser = new ArrayCollection();
    }
}
