HandissimoBundle\Entity\Brochures:
    type: entity
    table: null
    repositoryClass: HandissimoBundle\Repository\BrochuresRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        brochureName:
            type: string
            length: 255
        updatedAt:
            type: datetime
        brochureSize:
            type: integer
    lifecycleCallbacks: {  }
