HandissimoBundle\Entity\CommentAnswer:
    type: entity
    table: null
    repositoryClass: HandissimoBundle\Repository\CommentAnswerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        author:
            type: string
            length: 255
        parutionDate:
            type: datetime
        content:
            type: text
        title:
            type: string
            length: 255
        statusComment:
            type: boolean
            nullable: true
        likeAnswer:
            type: integer
            nullable: true
        dislikeAnswer:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }
