HandissimoBundle\Entity\Society:
    type: entity
    table: society
    repositoryClass: HandissimoBundle\Repository\SocietyRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        societyname:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: societyname
        logo:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        address:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        postal:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        city:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        phoneNumber:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: phone_number
        mail:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        societyTwitter:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: society_twitter
        societyFacebook:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: society_facebook
        website:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false

    oneToOne:
        userSociety:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            inversedBy: societyUser
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE

    oneToMany:
        organization:
            targetEntity: Organizations
            mappedBy: societies

    lifecycleCallbacks: {  }
