HandissimoBundle\Entity\StructuresList:
    type: entity
    table: null
    repositoryClass: HandissimoBundle\Repository\StructuresListRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        structureType:
            type: array
            nullable: true

    oneToOne:
        organizationsStructure:
            targetEntity: HandissimoBundle\Entity\Organizations
            mappedBy: orgaStructure



    lifecycleCallbacks: {  }
