HandissimoBundle\Entity\StructuresList:
    type: entity
    table: null
    repositoryClass: HandissimoBundle\Repository\StructuresListRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255

    oneToOne:
        organizationsStructure:
            targetEntity: HandissimoBundle\Entity\Organizations
            inversedBy: orgaStructure
            joinColumn:
                name: organizations_id
            targetEntity: StructuresTypes
            inversedBy: orgastructuretype
            joinColumn:
                name: structurestypes_id
                referencedColumnName: id

    lifecycleCallbacks: {  }
