HandissimoBundle\Entity\StructureType:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        picture:
            type: string
            length: 255
            nullable: true
        pictureUpdatedAt:
            type: datetime
            nullable: true

    oneToMany:
        structure:
            targetEntity: HandissimoBundle\Entity\StructuresList
            mappedBy: type

    lifecycleCallbacks: {  }
