HandissimoBundle\Entity\StructuresList:
    type: entity
    table: null
    repositoryClass: HandissimoBundle\Repository\StructuresListRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255


    oneToOne:
        organizationsStructure:
            targetEntity: HandissimoBundle\Entity\Organizations
            mappedBy: orgaStructure

    manyToOne:
        type:
            targetEntity: HandissimoBundle\Entity\StructureType
            inversedBy: structure
            joinColumn:
                name: type_id
                referencedColunName: id

    lifecycleCallbacks: {  }
