HandissimoBundle\Entity\StructuresTypes:
    type: entity
    table: structures_types
    repositoryClass: HandissimoBundle\Repository\StructuresTypesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        structurestype:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: structurestype

    oneToMany:
        organizationtype:
            targetEntity: Organizations
            mappedBy: structuretype

        orgastructuretype:
            targetEntity: HandissimoBundle\Entity\StructuresList
            mappedBy: structurelists
            cascade: [ persist ]
            orphanRemoval: true

    lifecycleCallbacks: {  }
