HandissimoBundle\Entity\Test:
    type: entity
    table: null
    repositoryClass: HandissimoBundle\Repository\TestRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        geom:
            type: point
            unique: true
            requireSQLConversion: true
        tags:
            type: string
            length: 255
    lifecycleCallbacks: {  }
